name: Deploy public website

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy public website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Configure AWS CloudFormation stack name
      id: stack-name
      env:
        REPO: ${{ github.repository }}
      run: |
        STACK_NAME=$(echo $REPO | tr '/' '-' | tr '[:upper:]' '[:lower:]')
        echo "Stack name: $STACK_NAME"
        echo "::set-output name=stack_name::$STACK_NAME"

    - name: Deploy to AWS CloudFormation
      id: cloudformation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ steps.stack-name.outputs.stack_name }}
        template: cloudformation.yml
        no-fail-on-empty-changeset: 1
        parameter-overrides: >-
          DomainName=${{ secrets.DOMAIN }},
          HostedZoneId=${{ secrets.AWS_HOSTED_ZONE_ID }},
          ExistingAcmCertificate=${{ secrets.AWS_ACM_ARN }},
          LogPrefix=${{ secrets.DOMAIN }},
          UserArn=${{ secrets.AWS_USER_ARN }}

    - name: Copy files to s3
      env:
        BUCKET: ${{ steps.cloudformation.outputs.BucketName }}
      run: |
        echo "Copying files to $BUCKET"
        aws s3 sync --delete public/ "s3://$BUCKET"

    - name: Create CloudFront distribution invalidation
      env:
        CLOUDFRONT_DISTRIBUTION: ${{ steps.cloudformation.outputs.CloudfrontDistributionId }}
      run: |
         echo Cloudfront distribution ID: "$CLOUDFRONT_DISTRIBUTION"
         aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*"